name: ctchat
channels:
  - defaults
dependencies:
  - python=3.12.5
  - pip=24.2
  - pip:
      # - torch==2.4.0
      # - torchvision==0.19.0
      # - torchaudio==2.4.0
      - torchmetrics==1.5.2
      - torchtyping==0.1.5
      - numpy==1.26.3
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - matplotlib
      - tqdm
      - transformers
      - uvicorn
      - fastapi==0.115.4
      - pillow==10.2.0
      - scipy==1.14.1
      - wandb==0.19.2
      - ninja==1.11.1.3
      - notebook
# pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124